# Generated by Django 3.0.6 on 2020-05-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='points',
        ),
        migrations.AddField(
            model_name='myuser',
            name='points_buy',
            field=models.PositiveIntegerField(default=0, verbose_name='Direct Points'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='points_img',
            field=models.PositiveIntegerField(default=0, verbose_name='ImgReview Points'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='points_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Points'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='points_vid',
            field=models.PositiveIntegerField(default=0, verbose_name='VidReview Points'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Birthday'),
        ),
    ]
