# Generated by Django 3.0.6 on 2020-05-30 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200530_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='points_total',
        ),
    ]
